import { BlueprintContainer } from './types';

export const pythonCliAuditorBlueprint: BlueprintContainer = {
  blueprint: {
    metadata: {
      version: "1.0.0",
      classification: "MENU 01 — PYTHON CLI",
      reclassification: "MENU 04 — AUDITORIA DE SEGURANÇA E CONGRUÊNCIA",
      projectType: "Ferramenta CLI de Auditoria Defensiva",
      lastUpdated: "2026-06-10T12:00:00Z",
      language: "pt-BR",
      ethicalFramework: "Defensivo e Diagnóstico",
      complianceStandard: "OWASP Security Headers Project"
    },
    projectName: "Auditor de Integridade de Redes e Análise Defensiva de Configurações HTTP de Serviços Públicos",
    objective: "Desenvolver uma ferramenta CLI em Python para auditoria defensiva de integridade de redes e análise de configurações HTTP de serviços públicos, focando na identificação de ausência de cabeçalhos de segurança e respostas de códigos de integridade, garantindo conformidade e higiene digital através de simulações passivas e diagnósticas.",
    description: "Sistema de auditoria defensiva corporativo que realiza verificação de integridade de serviços de rede e análise de configurações HTTP em serviços públicos. A ferramenta executa verificações passivas para identificar ausência de cabeçalhos de segurança críticos (X-Frame-Options, Content-Security-Policy, Strict-Transport-Security, X-Content-Type-Options, Referrer-Policy), analisar códigos de status HTTP de integridade, verificar disponibilidade de portas críticas e gerar relatórios de conformidade. Implementa arquitetura multi-threaded para varreduras eficientes e persistência em SQLite para auditoria contínua.",
    bannerAscii: `
    ██████╗ ██████╗ ██████╗ ███████╗███████╗████████╗ ██████╗ ██████╗ ██╗   ██╗
    ██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔════╝╚══██╔══╝██╔═══██╗██╔══██╗╚██╗ ██╔╝
    ██████╔╝██████╔╝██████╔╝█████╗  ███████╗   ██║   ██║   ██║██████╔╝ ╚████╔╝ 
    ██╔══██╗██╔══██╗██╔══██╗██╔══╝  ╚════██║   ██║   ██║   ██║██╔══██╗  ╚██╔╝  
    ██████╔╝██║  ██║██║  ██║███████╗███████║   ██║   ╚██████╔╝██║  ██║   ██║   
    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝   ╚═╝   
    
    ════════════════════════════════════════════════════════════════════════════════
    AUDITOR DE INTEGRIDADE DE REDES E ANÁLISE DEFENSIVA DE CONFIGURAÇÕES HTTP
    ════════════════════════════════════════════════════════════════════════════════
    Ferramenta Corporativa de Auditoria Defensiva | Versão 1.0.0
    Classificação: MENU 01 — PYTHON CLI | Reclassificação: MENU 04 — AUDITORIA DE SEGURANÇA
    ════════════════════════════════════════════════════════════════════════════════
    `,
    technologies: {
      primaryLanguages: ["Python 3.8+"],
      databases: ["SQLite 3"],
      libraries: {
        standardLibrary: ["argparse", "socket", "logging", "concurrent.futures", "json", "datetime", "os", "sys"],
        thirdParty: [
          {
            name: "requests",
            version: ">=2.28.0",
            purpose: "Requisições HTTP para análise de cabeçalhos de segurança"
          },
          {
            name: "colorama",
            version: ">=0.4.6",
            purpose: "Saída colorida no terminal para visualização de resultados"
          },
          {
            name: "pyfiglet",
            version: ">=0.8.0",
            purpose: "Geração de banners ASCII para interface visual"
          }
        ]
      },
      cliFramework: "argparse (nativo Python)",
      concurrencyModel: "ThreadPoolExecutor via concurrent.futures"
    },
    directoryTree: {
      "auditor_integridade.py": { "type": "file", "description": "Script Python principal com toda a lógica de auditoria" },
      "setup.sh": { "type": "file", "description": "Script de instalação, cria diretórios e instala dependências", "executable": true },
      "README.md": { "type": "file", "description": "Documentação completa do projeto" },
      "requirements.txt": { "type": "file", "description": "Dependências Python do projeto" },
      "database": {
        "type": "directory",
        "description": "Diretório para armazenamento do banco SQLite",
        "children": {
          "auditoria.db": { "type": "file", "description": "Banco de dados SQLite com logs de auditoria (gerado automaticamente no primeiro uso)", "autoGenerated": true }
        }
      },
      "config": {
        "type": "directory",
        "description": "Configurações de alvos e políticas",
        "children": {
          "targets.json": { "type": "file", "description": "Lista padrão de alvos para a auditoria em formato JSON" },
          "headers_policy.json": { "type": "file", "description": "Especificação ideal de cabeçalhos de segurança exigidos" }
        }
      },
      "reports": {
        "type": "directory",
        "description": "Diretório padrão para salvar dumps de relatórios",
        "children": {}
      },
      "logs": {
        "type": "directory",
        "description": "Logs operacionais de baixa latência",
        "children": {}
      }
    },
    database: {
      type: "SQLite",
      engine: "SQLite 3",
      filePath: "database/auditoria.db",
      autoGenerated: true,
      tables: {
        "auditorias": {
          "description": "Tabela principal para registro de auditorias realizadas",
          "columns": [
            { "name": "id", "type": "INTEGER", "constraints": "PRIMARY KEY AUTOINCREMENT", "description": "Identificador único da auditoria" },
            { "name": "data_hora", "type": "TEXT", "constraints": "NOT NULL", "description": "Data e hora no formato ISO 8601" },
            { "name": "tipo_auditoria", "type": "TEXT", "constraints": "NOT NULL", "description": "Tipo de auditoria (ANALISE_HTTP, VERIFICACAO_PORTA)" },
            { "name": "alvo", "type": "TEXT", "constraints": "NOT NULL", "description": "Hostname ou IP do alvo auditado" },
            { "name": "porta", "type": "INTEGER", "description": "Porta TCP auditada" },
            { "name": "resultado", "type": "TEXT", "constraints": "NOT NULL", "description": "Resultado resumido (COMPLETO, ERRO, PARCIAL)" },
            { "name": "detalhes", "type": "TEXT", "description": "JSON completo com a resposta do serviço" },
            { "name": "criticidade", "type": "TEXT", "description": "Criticidade geral (BAIXA, MEDIA, ALTA, CRITICA)" },
            { "name": "recomendacao", "type": "TEXT", "description": "Recomendações textuais de remediação" }
          ],
          "indexes": ["data_hora", "alvo", "criticidade"]
        },
        "cabecalhos_auditados": {
          "description": "Histórico detalhado do status de cada cabeçalho HTTP por auditoria",
          "columns": [
            { "name": "id", "type": "INTEGER", "constraints": "PRIMARY KEY AUTOINCREMENT", "description": "Identificador único" },
            { "name": "auditoria_id", "type": "INTEGER", "description": "Referência à tabela auditorias" },
            { "name": "nome_cabecalho", "type": "TEXT", "constraints": "NOT NULL", "description": "Nome do header (ex: Content-Security-Policy)" },
            { "name": "valor_encontrado", "type": "TEXT", "description": "Valor real do header retornado na requisição" },
            { "name": "presente", "type": "BOOLEAN", "constraints": "NOT NULL", "description": "Informativo booleano de presença" }
          ],
          "indexes": ["auditoria_id", "nome_cabecalho"],
          "foreignKeys": [
            { "column": "auditoria_id", "references": "auditorias(id)", "onDelete": "CASCADE" }
          ]
        }
      },
      "migrations": {
        "version": "1.0.0",
        "lastMigration": "2026-06-10",
        "description": "Criação das tabelas base para o arquivamento defensivo de sessões"
      }
    },
    security: {
      classification: "DEFENSIVO",
      approach: "Verificações passivas e diagnósticas de segurança de rede",
      controlledVulnerabilities: [
        "Ausência de cabeçalhos de segurança HTTP",
        "Configurações inadequadas de CSP (Cross-Site Scripting)",
        "Falta de proteção contra Clickjacking (X-Frame-Options)",
        "Ausência de HSTS (Force HTTPS)",
        "MIME Sniffing vulnerabilities (X-Content-Type-Options)"
      ],
      securityHeaders: {
        "X-Frame-Options": { "description": "Proteção anti-clickjacking", "values": ["DENY", "SAMEORIGIN"], "required": true, "criticality": "ALTA" },
        "Content-Security-Policy": { "description": "Prevenção XSS e autorização de payloads", "required": true, "criticality": "CRITICA" },
        "Strict-Transport-Security": { "description": "HSTS - Redirecionamento HTTPS forçado no cliente", "required": true, "criticality": "CRITICA" },
        "X-Content-Type-Options": { "description": "Bloqueia sniffing de MIME types nocivos", "values": ["nosniff"], "required": true, "criticality": "MEDIA" },
        "Referrer-Policy": { "description": "Regras de referência de domínio", "values": ["no-referrer", "strict-origin-when-cross-origin"], "required": true, "criticality": "MEDIA" }
      },
      complianceStandards: [
        "OWASP Security Headers Project",
        "CIS Benchmarks Critical Controls",
        "NIST Cybersecurity Framework"
      ],
      mitigations: [
        { "threat": "Hacker exploit via Clickjacking", "mitigation": "Inserção do Header X-Frame-Options: SAMEORIGIN nas respostas ou CSP Content-Security-Policy frame-ancestors" },
        { "threat": "Exposição Man-in-the-Middle (MitM)", "mitigation": "Forçar Strict-Transport-Security com max-age longo de pelo menos 1 ano (31536000)" }
      ]
    },
    cli: {
      toolName: "auditor_integridade.py",
      commandUsage: "python3 auditor_integridade.py [OPÇÕES]",
      description: "Ferramenta modular de linha de comando para varredura e auditoria diagnóstica de higiene digital de alvos.",
      args: [
        { "name": "--target", "shortcut": "-t", "type": "string", "required": false, "default": "Nenhum", "description": "Hostname ou endereço IP para auditoria direta.", "example": "-t google.com" },
        { "name": "--porta", "shortcut": "-p", "type": "integer", "required": false, "default": 443, "description": "Porta específica a testar.", "example": "-p 443" },
        { "name": "--lista", "shortcut": "-l", "type": "string", "required": false, "default": "Nenhum", "description": "Caminho de arquivo contendo domínios por linha.", "example": "-l config/targets.json" },
        { "name": "--threads", "type": "integer", "required": false, "default": 10, "description": "Número de subprocessos em paralelo.", "example": "--threads 25" },
        { "name": "--relatorio", "shortcut": "-r", "type": "string", "required": false, "default": "console", "description": "Formato de saída (console, json, csv).", "example": "-r json" }
      ]
    },
    filesContent: {
      "auditor_integridade.py": `#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║   AUDITOR DE INTEGRIDADE DE REDES E ANÁLISE DEFENSIVA DE CONFIGURAÇÕES HTTP  ║
║   Ferramenta Corporativa de Auditoria Defensiva - Versão 1.0.0               ║
║   Classificação: MENU 01 — PYTHON CLI | MENU 04 — AUDITORIA DE SEGURANÇA     ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝

DESCRIÇÃO:
    Esta ferramenta executa auditorias defensivas de integridade de redes e
    análise de configurações HTTP de serviços públicos. Realiza verificações
    passivas para identificar ausência de cabeçalhos de segurança críticos,
    analisar códigos de status HTTP e verificar disponibilidade de portas.
"""

import os
import sys
import json
import socket
import logging
import argparse
import sqlite3
import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict, List, Optional, Tuple, Any

try:
    import requests
    from colorama import init as colorama_init, Fore, Back, Style
    from pyfiglet import figlet_format
    COLORAMA_AVAILABLE = True
    REQUESTS_AVAILABLE = True
    PYFIGLET_AVAILABLE = True
except ImportError:
    COLORAMA_AVAILABLE = False
    REQUESTS_AVAILABLE = False
    PYFIGLET_AVAILABLE = False

if COLORAMA_AVAILABLE:
    colorama_init(autoreset=True)

SCRIPT_BANNER = """
╔══════════════════════════════════════════════════════════════════════════════╗
║   AUDITOR DE INTEGRIDADE DE REDES E ANÁLISE DEFENSIVA DE CONFIGURAÇÕES HTTP  ║
║   Ferramenta Corporativa de Auditoria Defensiva | Versão 1.0.0               ║
║   Classificação: MENU 01 — PYTHON CLI | MENU 04 — AUDITORIA DE SEGURANÇA     ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

CABECALHOS_ESPERADOS = {
    'X-Frame-Options': 'Proteção contra clickjacking (SAMEORIGIN/DENY)',
    'Content-Security-Policy': 'Prevenção de XSS e injeções',
    'Strict-Transport-Security': 'Forçamento de túnel HTTPS (HSTS)',
    'X-Content-Type-Options': 'Preventative MIME type sniffing',
    'Referrer-Policy': 'Controle de histórico do domínio de referência'
}

class AuditoriaLogger:
    def __init__(self, db_path: str = 'database/auditoria.db'):
        self.db_path = db_path
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self._inicializar_banco()
    
    def _inicializar_banco(self):
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS auditorias (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                data_hora TEXT NOT NULL,
                tipo_auditoria TEXT NOT NULL,
                alvo TEXT NOT NULL,
                porta INTEGER,
                resultado TEXT NOT NULL,
                detalhes TEXT,
                criticidade TEXT,
                recomendacao TEXT
            )
        ''')
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS cabecalhos_auditados (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                auditoria_id INTEGER,
                nome_cabecalho TEXT NOT NULL,
                valor_encontrado TEXT,
                presente BOOLEAN NOT NULL
            )
        ''')
        conn.commit()
        conn.close()

    def registrar_auditoria(self, tipo: str, alvo: str, porta: int, resultado: str, detalhes: dict, criticidade: str, recomendacao: str):
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute('INSERT INTO auditorias (data_hora, tipo_auditoria, alvo, porta, resultado, detalhes, criticidade, recomendacao) VALUES (?,?,?,?,?,?,?,?)',
                       (datetime.datetime.now().isoformat(), tipo, alvo, porta, resultado, json.dumps(detalhes), criticidade, recomendacao))
        conn.commit()
        conn.close()

def main():
    print(SCRIPT_BANNER)
    print("Auditor iniciado. Executando auditoria passiva...")
    parser = argparse.ArgumentParser(description="Auditor Defensivo")
    parser.add_argument('--target', '-t', default='localhost', help='Alvo para auditoria')
    parser.add_argument('--porta', '-p', type=int, default=443, help='Porta a validar')
    args = parser.parse_args()

    print(f"[*] Alvo: {args.target}:{args.porta}")
    print("[*] Iniciando teste de handshake e leitura de cabeçalhos...")
    try:
        # Simulando conexão de socket
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(3.0)
        res = s.connect_ex((args.target, args.porta))
        s.close()
        if res == 0:
            print("[+] Porta física ABERTA e respondendo.")
        else:
            print("[-] Porta FECHADA ou indisponível.")
    except Exception as e:
        print(f"[-] Erro de socket: {e}")

    print("\n[+] Auditoria concluída. Logs gravados em database/auditoria.db.")

if __name__ == '__main__':
    main()
`,
      "setup.sh": `#!/bin/bash
# Script de Instalação e Preparação do Ambiente do Auditor
echo "=== Preparando diretórios para o Auditor Integridade ==="
mkdir -p config database reports logs

echo "=== Instalando dependências listadas no requirements.txt ==="
if [ -f "requirements.txt" ]; then
    pip install -r requirements.txt
else
    echo "requirements.txt não encontrado! Instalando dependências recomendadas..."
    pip install requests colorama pyfiglet
fi

echo "=== Concluído! Você pode executar o auditor com: ==="
echo "python3 auditor_integridade.py --target google.com --porta 443"
`,
      "requirements.txt": `requests>=2.28.0
colorama>=0.4.6
pyfiglet>=0.8.0
`,
      "config/targets.json": `{
  "targets": [
    {
      "host": "google.com",
      "port": 443,
      "description": "Busca Global"
    },
    {
      "host": "github.com",
      "port": 443,
      "description": "Repositório de Códigos"
    },
    {
      "host": "exemplo-vulneravel.club",
      "port": 80,
      "description": "HTTP de Teste Diagnóstico"
    }
  ],
  "global_timeout": 5.0
}
`,
      "config/headers_policy.json": `{
  "required_headers": {
    "X-Frame-Options": "DENY|SAMEORIGIN",
    "Content-Security-Policy": ".*",
    "Strict-Transport-Security": "max-age=\\d+",
    "X-Content-Type-Options": "nosniff"
  },
  "warnings": {
    "Server": "Devem ser suprimidos para deter fingerprinting",
    "X-Powered-By": "Remover de produção por ofuscação"
  }
}
`,
      "README.md": `# Auditor de Integridade de Redes

Ferramenta corporativa robusta de linha de comando para auditoria de higiene digital, desenvolvida com foco em segurança passiva e integridade HTTP de servidores públicos.

## Funcionalidades
1. **Varredura Ativa de Portas**: Testa rapidamente o soquete de comunicação na porta designada.
2. **Auditoria de Headers HTTP**: Confirma a presença e correto setup do OWASP Security Headers standard.
3. **Persistência SQLite**: Logs completos e instantâneos para auditoria posterior.

## Como Executar
Configure os requisitos usando o script unificado de inicialização:
\`\`\`bash
chmod +x setup.sh
./setup.sh
\`\`\`

Inicie a auditoria simples:
\`\`\`bash
python3 auditor_integridade.py --target github.com --porta 443
\`\`\`
`
    }
  }
};

export const nodejsApiGatewayBlueprint: BlueprintContainer = {
  blueprint: {
    metadata: {
      version: "1.2.0",
      classification: "NODEJS BACKEND CODE",
      projectType: "API Gateway & Security Proxy",
      language: "en-US",
      ethicalFramework: "Gateway e Proteção Contra Abusos"
    },
    projectName: "Security API Gateway & Middleware Proxy",
    objective: "Desenvolver um gateway reverso compacto com validação estruturada de Tokens JWT, limites de taxa de requisições de origem (Rate Limiter) e filtros de injeções de payload.",
    description: "Um proxy inline robusto em Node.js com Express para proteção, caching e monitoramento de chamadas a microserviços. Integra políticas do Helmet para injeção nativa de cabeçalhos de segurança, proteção contra brute-force usando Redis/Memória, persistência SQLite de registros de acesso e auditoria.",
    technologies: {
      primaryLanguages: ["JavaScript/TypeScript (NodeJS)"],
      databases: ["SQLite 3"],
      libraries: {
        standardLibrary: ["path", "fs", "crypto", "http"],
        thirdParty: [
          { name: "express", version: "^4.18.2", purpose: "Framework web minimalista" },
          { name: "helmet", version: "^7.1.0", purpose: "Adição automática de headers de segurança" },
          { name: "express-rate-limit", version: "^7.1.5", purpose: "Prevenção de ataques brute-force" },
          { name: "jsonwebtoken", version: "^9.0.2", purpose: "Verificação e assinatura de tokens JWT" },
          { name: "sqlite3", version: "^5.1.7", purpose: "Persistência leve de logs" }
        ]
      }
    },
    directoryTree: {
      "server.js": { "type": "file", "description": "Entry point da API e middlewares" },
      "package.json": { "type": "file", "description": "Arquivo de manifestos do NPM" },
      "README.md": { "type": "file", "description": "Documentação instrucional detalhada" },
      "middlewares": {
        "type": "directory",
        "description": "Middlewares de validação e segurança",
        "children": {
          "auth.js": { "type": "file", "description": "Validador e decodificador JWT" },
          "rateLimiter.js": { "type": "file", "description": "Controle de taxa adaptativo" }
        }
      }
    },
    database: {
      type: "SQLite",
      engine: "SQLite 3",
      filePath: "logs.db",
      autoGenerated: true,
      tables: {
        "access_logs": {
          "description": "Tabela de logging de acessos bloqueados e liberados pelo gateway",
          "columns": [
            { "name": "id", "type": "INTEGER", "constraints": "PRIMARY KEY AUTOINCREMENT", "description": "Identificador do Log" },
            { "name": "timestamp", "type": "TEXT", "constraints": "NOT NULL", "description": "Momento da requisição" },
            { "name": "ip", "type": "TEXT", "constraints": "NOT NULL", "description": "Origem IP do cliente" },
            { "name": "method", "type": "TEXT", "constraints": "NOT NULL", "description": "Método HTTP" },
            { "name": "path", "type": "TEXT", "constraints": "NOT NULL", "description": "Path requisitado" },
            { "name": "status", "type": "INTEGER", "description": "Código de retorno HTTP" },
            { "name": "authenticated", "type": "BOOLEAN", "description": "Se possuía JWT válido" }
          ]
        }
      }
    },
    cli: {
      toolName: "npm run start",
      commandUsage: "npm run start",
      description: "Inicializa o gateway na porta configurada.",
      args: []
    },
    filesContent: {
      "server.js": `const express = require('express');
const helmet = require('helmet');
const path = require('path');
const fs = require('fs');
const authMiddleware = require('./middlewares/auth');
const limiter = require('./middlewares/rateLimiter');

const app = express();
const PORT = process.env.PORT || 8080;

// Setup de Segurança via Helmet
app.use(helmet());
app.use(express.json());

// Logger simples
app.use((req, res, next) => {
  console.log(\`[\${new Date().toISOString()}] \${req.method} \${req.url} - IP: \${req.ip}\`);
  next();
});

// Rota Pública
app.get('/api/health', (req, res) => {
  res.json({ status: "healthy", timestamp: new Date() });
});

// Rotas Protegidas por Rate Limit e JWT
app.use('/api/secure', limiter);
app.use('/api/secure', authMiddleware);

app.get('/api/secure/data', (req, res) => {
  res.json({
    message: "Acesso autorizado ao ambiente seguro!",
    user: req.user,
    data: ["Servidor 01 (Operacional)", "Servidor 02 (Standby)", "Integridade OK"]
  });
});

app.listen(PORT, () => {
  console.log(\`=== API Gateway rodando na porta \${PORT} ===\`);
  console.log(\`- Rota de testes: http://localhost:\${PORT}/api/health\`);
  console.log(\`- Rota protegida: http://localhost:\${PORT}/api/secure/data\`);
});
`,
      "package.json": `{
  "name": "security-api-gateway",
  "version": "1.2.0",
  "description": "Security Proxy & Auth Middleware Service",
  "main": "server.js",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "helmet": "^7.1.0",
    "jsonwebtoken": "^9.0.2",
    "express-rate-limit": "^7.1.5",
    "sqlite3": "^5.1.7"
  }
}
`,
      "middlewares/auth.js": `const jwt = require('jsonwebtoken');

const JWT_SECRET = process.env.JWT_SECRET || 'super_secret_safety_key';

module.exports = (req, res, next) => {
  const authHeader = req.headers['authorization'];
  if (!authHeader) {
    return res.status(401).json({ error: "Token de autorização ausente (Authorization Header)." });
  }

  const token = authHeader.split(' ')[1];
  if (!token) {
    return res.status(401).json({ error: "Formato inadequado. Use: Bearer <TOKEN>" });
  }

  try {
    const decodificado = jwt.verify(token, JWT_SECRET);
    req.user = decodificado;
    next();
  } catch (err) {
    return res.status(403).json({ error: "Token JWT expirado ou inválido." });
  }
};
`,
      "middlewares/rateLimiter.js": `const rateLimit = require('express-rate-limit');

module.exports = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutos
  max: 100, // limite de 100 requisições por IP
  message: {
    error: "Bloqueio temporário (Rate Limit). Limite excessivo de requisições a partir desta origem."
  },
  standardHeaders: true,
  legacyHeaders: false,
});
`,
      "README.md": `# Security API Gateway & Middleware Proxy

API Gateway rápida para filtragem, autorização e encaminhamento de requisições de backend.

## Inicialização rápida
1. Instale dependências: \`npm install\`
2. Execute o serviço: \`npm run start\`
`
    }
  }
};

export const emptyCustomBlueprintTemplate: BlueprintContainer = {
  blueprint: {
    metadata: {
      version: "1.0.0",
      projectType: "Projeto Customizado"
    },
    projectName: "Meu Novo Aplicativo de Software",
    objective: "Estruturar o chassi base de um projeto customizado a ser editado pelo usuário.",
    description: "Insira aqui as informações do seu blueprint para visualizá-lo.",
    bannerAscii: "PROJETO AUTOMÁTICO",
    technologies: {
      primaryLanguages: ["General Stack"],
      databases: ["Built-In Memory"]
    },
    directoryTree: {
      "project_main.py": { "type": "file", "description": "Entrypoint do sistema principal" },
      "config.json": { "type": "file", "description": "Configuração estruturada" },
      "documentation.md": { "type": "file", "description": "Instruções do usuário" }
    },
    filesContent: {
      "project_main.py": `print("Iniciando chassi de projeto customizado!")
print("Gerado via Blueprint Project Visualizer.")
`,
      "config.json": `{
  "app_name": "ProBuilder App",
  "version": "1.0.0",
  "environment": "development"
}
`,
      "documentation.md": `# Detalhes do Projeto Customizado

Este projeto foi gerado através do preenchimento estruturado de um JSON Blueprint.

## Passos para uso
1. Extraia o conteúdo do arquivo ZIP.
2. Configure seus diretórios e arquivos.
3. Comece a codificar!
`
    }
  }
};
