export interface BlueprintMetadata {
  version: string;
  classification?: string;
  reclassification?: string;
  projectType: string;
  lastUpdated?: string;
  language?: string;
  ethicalFramework?: string;
  complianceStandard?: string;
  isLocalFallback?: boolean;
  fallbackExplanation?: string;
}

export interface TechnologyLibrary {
  name: string;
  version: string;
  purpose: string;
}

export interface BlueprintTechnologies {
  primaryLanguages: string[];
  databases: string[];
  libraries?: {
    standardLibrary?: string[];
    thirdParty?: TechnologyLibrary[];
  };
  cliFramework?: string;
  concurrencyModel?: string;
}

export interface DatabaseColumn {
  name: string;
  type: string;
  constraints?: string;
  description?: string;
}

export interface DatabaseTable {
  description: string;
  columns: DatabaseColumn[];
  indexes?: string[];
  foreignKeys?: any[];
}

export interface DatabaseSchema {
  type: string;
  engine: string;
  filePath: string;
  tables: Record<string, DatabaseTable>;
  autoGenerated?: boolean;
  migrations?: {
    version: string;
    lastMigration: string;
    description: string;
  };
}

export interface SecurityHeaderPolicy {
  description?: string;
  values?: string[] | null;
  required?: boolean;
  criticality?: string;
}

export interface SecurityMitigation {
  threat: string;
  mitigation: string;
}

export interface BlueprintSecurity {
  classification?: string;
  approach?: string;
  controlledVulnerabilities?: string[];
  securityHeaders?: Record<string, SecurityHeaderPolicy>;
  complianceStandards?: string[];
  auditLogRetention?: {
    description: string;
    period: string;
    archivePolicy: string;
    retentionLocation: string;
  };
  mitigations?: SecurityMitigation[];
  scanPolicy?: {
    passiveMode?: boolean;
    noActiveExploitation?: boolean;
    noPayloadInjection?: boolean;
    noBruteForce?: boolean;
    noCredentialTesting?: boolean;
    complianceOnly?: boolean;
    ethicalGuideline?: string;
  };
}

export interface CliArgument {
  name: string;
  shortcut?: string;
  type: string;
  required: boolean;
  default: any;
  choices?: string[];
  description: string;
  example: string;
}

export interface BlueprintCli {
  toolName: string;
  commandUsage: string;
  description: string;
  args?: CliArgument[];
}

export interface DirectoryNode {
  type: 'directory' | 'file';
  description?: string;
  size?: string;
  encoding?: string;
  executable?: boolean;
  autoGenerated?: boolean;
  children?: Record<string, DirectoryNode>;
}

export interface ProjectBlueprint {
  metadata: BlueprintMetadata;
  projectName: string;
  objective: string;
  description: string;
  bannerAscii?: string;
  technologies?: BlueprintTechnologies;
  directoryTree?: Record<string, any>; // recursive
  database?: DatabaseSchema;
  security?: BlueprintSecurity;
  cli?: BlueprintCli;
  setup_sh?: {
    scriptName: string;
    description: string;
    content: string;
  };
  filesContent?: Record<string, string>; // Maps file paths (e.g. "auditor_integridade.py") to content
}

export interface BlueprintContainer {
  blueprint: ProjectBlueprint;
}
