import { DirectoryNode } from './types';

export interface FlatFileNode {
  path: string;
  name: string;
  type: 'file' | 'directory';
  level: number;
  description?: string;
  isOpen?: boolean;
}

/**
 * Traverses a recursive directory tree inside a blueprint and returns a flat representation 
 * of nodes with correct relative paths, nested levels, and files.
 */
export function flattenDirectoryTree(
  tree: Record<string, any>,
  parentPath = '',
  level = 0
): FlatFileNode[] {
  let nodes: FlatFileNode[] = [];

  // Sort directories first, then files
  const entries = Object.entries(tree).sort((a, b) => {
    const typeA = a[1].type || 'file';
    const typeB = b[1].type || 'file';
    if (typeA === 'directory' && typeB === 'file') return -1;
    if (typeA === 'file' && typeB === 'directory') return 1;
    return a[0].localeCompare(b[0]);
  });

  for (const [name, data] of entries) {
    const currentPath = parentPath ? `${parentPath}/${name}` : name;
    const isDir = data.type === 'directory';

    nodes.push({
      path: currentPath,
      name,
      type: isDir ? 'directory' : 'file',
      level,
      description: data.description,
      isOpen: true,
    });

    if (isDir && data.children) {
      nodes = [...nodes, ...flattenDirectoryTree(data.children, currentPath, level + 1)];
    }
  }

  return nodes;
}

/**
 * Inspects a blueprint, ensuring its filesContent matches what's listed in directory tree.
 * Re-maps files that were generated by setup scripts or setup_sh.
 */
export function sanitizeBlueprintFiles(blueprint: any): Record<string, string> {
  const files: Record<string, string> = { ...(blueprint.filesContent || {}) };

  // Recursively traverse directory tree and populate missing file contents so files inside folders are never blank/empty
  if (blueprint.directoryTree) {
    const walkTree = (tree: Record<string, any>, currentPrefix = '') => {
      for (const [name, data] of Object.entries(tree)) {
        const fullPath = currentPrefix ? `${currentPrefix}/${name}` : name;
        if (data.type === 'directory') {
          if (data.children) {
            walkTree(data.children, fullPath);
          }
        } else {
          // It's a file. If it has no content, create an informative and robust placeholder
          if (files[fullPath] === undefined) {
            const desc = data.description || 'Arquivo operacional gerado automaticamente.';
            if (fullPath.endsWith('.json')) {
              files[fullPath] = JSON.stringify({
                status: 'CONCLUÍDO',
                origem: 'Configuração Automática do Chassi',
                descricao: desc,
                timestamp: new Date().toISOString()
              }, null, 2);
            } else if (fullPath.endsWith('.db') || fullPath.endsWith('.sqlite')) {
              files[fullPath] = `[Banco de Dados SQLite em disco: /${fullPath}]\n\nEste arquivo codifica o banco de dados relacional local do chassi configurado.\nTabelas simuladas e gerenciamento integrado ativo.\nStatus: INICIALIZADO\nPropósito: ${desc}`;
            } else if (fullPath.endsWith('.md')) {
              files[fullPath] = `# ${name}\n\n${desc}\n\n*Gerado dinamicamente para manter a integridade dos diretórios de compliance.*`;
            } else if (fullPath.endsWith('.py')) {
              files[fullPath] = `#!/usr/bin/env python3\n# -*- coding: utf-8 -*-\n# ${name}\n# ${desc}\n\nprint("Inicializando subsistema: ${name}")\n`;
            } else if (fullPath.endsWith('.js') || fullPath.endsWith('.ts')) {
              files[fullPath] = `/**\n * ${name}\n * ${desc}\n */\nconsole.log("Subsistema integrado: ${name} ativo.");\n`;
            } else {
              files[fullPath] = `# ${name}\n# Tipo: Arquivo de Suporte\n# Descrição: ${desc}\n`;
            }
          }
        }
      }
    };
    walkTree(blueprint.directoryTree);
  }

  // Fallback to extract content from setup_sh if present and not already mapped
  if (blueprint.setup_sh && blueprint.setup_sh.content && !files[blueprint.setup_sh.scriptName || 'setup.sh']) {
    files[blueprint.setup_sh.scriptName || 'setup.sh'] = blueprint.setup_sh.content;
  }

  // Ensure standard files are filled if empty
  if (Object.keys(files).length === 0) {
    files['README.md'] = `# ${blueprint.projectName || 'Projeto'}\n\n${blueprint.description || ''}\n\n## Objetivo\n${blueprint.objective || ''}`;
  }

  return files;
}

/**
 * Format filesizes for display
 */
export function formatSize(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}
